name: Deploy Next.js to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/nextjs-app || mkdir -p /home/ec2-user/nextjs-app && cd /home/ec2-user/nextjs-app
            
            git pull origin main || git clone -b main https://${{ secrets.GH_TOKEN }}@github.com/liutyinazar/xedrum-web.git .
            
            sudo docker-compose down
            sudo docker-compose up -d --build
